#!/bin/bash -e

# run from root of repo: `cd .git/hooks && ln -s -f ../../docs/hooks/* ./`
# the -e flag in the shebang line ensures that this hook exits if any of its commands exits with a non-zero exit status

python docs/contents.py docs/body.md > docs/contents.md
python docs/build.py docs/header.md docs/features.md docs/contents.md docs/body.md > README.md

# the -u flag updates and removes index entries, but adds nothing
git add docs/contents.md
git add README.md
