#!/bin/bash -e

# run from root of repo: `cd .git/hooks && ln -s -f ../../docs/_hooks/* ./`
# the -e flag in the shebang line ensures that this hook exits if any of its commands exits with a non-zero exit status

python docs/toc.py docs/_content/body.md > docs/_content/toc.md
BASE='docs/_content' && python docs/build.py $BASE/header.md $BASE/features.md $BASE/intro.md $BASE/releases.md $BASE/why_requester.md $BASE/youtube.md > README.md

git add docs/_content/toc.md
git add README.md
